In [1]:
import numpy as np
import pandas as pd
import sklearn

import time
from sklearn import linear_model
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn import preprocessing
from sklearn import metrics
from sklearn.metrics import accuracy_score
encode = LabelEncoder() 


In [2]:
data=pd.read_csv('data.csv')
data.describe()

print(data)


      Unnamed: 0  acousticness  danceability  duration_ms  energy  \
0              0      0.010200         0.833       204600   0.434   
1              1      0.199000         0.743       326933   0.359   
2              2      0.034400         0.838       185707   0.412   
3              3      0.604000         0.494       199413   0.338   
4              4      0.180000         0.678       392893   0.561   
5              5      0.004790         0.804       251333   0.560   
6              6      0.014500         0.739       241400   0.472   
7              7      0.020200         0.266       349667   0.348   
8              8      0.048100         0.603       202853   0.944   
9              9      0.002080         0.836       226840   0.603   
10            10      0.057200         0.525       358187   0.855   
11            11      0.091500         0.753       324880   0.748   
12            12      0.253000         0.603       356973   0.434   
13            13      0.366000    

In [7]:
data.head()

Unnamed: 0  acousticness  danceability  duration_ms  energy  \
0           0        0.0102         0.833       204600   0.434   
1           1        0.1990         0.743       326933   0.359   
2           2        0.0344         0.838       185707   0.412   
3           3        0.6040         0.494       199413   0.338   
4           4        0.1800         0.678       392893   0.561   

   instrumentalness  key  liveness  loudness  speechiness    tempo  \
0          0.021900    2    0.1650    -8.795       0.4310  150.062   
1          0.006110    1    0.1370   -10.401       0.0794  160.083   
2          0.000234    2    0.1590    -7.148       0.2890   75.044   
3          0.510000    5    0.0922   -15.236       0.0261   86.468   
4          0.512000    5    0.4390   -11.648       0.0694  174.004   

   time_signature  valence  mode      song_title            artist  target  
0               4    0.286     1        Mask Off            Future       1  
1               4    0.588     1         Redbone  Childish Gambino       1  
2               4    0.173     1    Xanny Family            Future       1  
3               4    0.230     1  Master Of None       Beach House       1  
4               4    0.904     0  Parallel Lines       Junior Boys       1

In [8]:
x=data.iloc[:,0:16].values
y=data.iloc[:,16].values

x[:,14] = encode.fit_transform(x[:,14])
x[:,15] = encode.fit_transform(x[:,15])
print(x)

[[0 0.0102 0.833 ... 1 1043 449]
 [1 0.19899999999999998 0.743 ... 1 1334 222]
 [2 0.0344 0.838 ... 1 1906 449]
 ...
 [2014 0.00857 0.637 ... 1 663 947]
 [2015 0.00164 0.557 ... 1 548 1242]
 [2016 0.00281 0.446 ... 1 788 132]]


In [20]:
X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=.50,random_state=200)
print("Train = ",len(X_train))
print("Test = ",len(X_test))

Train =  1008
Test =  1009


In [21]:
#Implementing Naive Bayes 

start_time=time.time()
GaussNb=GaussianNB()
GaussNb.fit(X_train,Y_train)

y_pred=GaussNb.predict(X_test)
accuracy= accuracy_score(Y_test,y_pred)*100
print("Execution time: ",time.time()-start_time)
print("Test Accuracy: ",round(accuracy,1),"%")

Execution time:  0.006982088088989258
Test Accuracy:  98.6 %


In [22]:
#Implementing Decision Tree
start_time=time.time()
DecisionTree=DecisionTreeClassifier(random_state=200)
DecisionTree.fit(X_train,Y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=200,
            splitter='best')

In [23]:
y_prede=DecisionTree.predict(X_test)
accuracy=accuracy_score(Y_test,y_prede)*100
print("Execution time: ",time.time()-start_time)
print("Test Accuracy: ",round(accuracy,1),"%")

Execution time:  0.8165714740753174
Test Accuracy:  99.1 %


In [24]:
#Implementing Neural network
start_time=time.time()
clf = MLPClassifier(solver='lbfgs', alpha=1e-5,  hidden_layer_sizes=(10, 5), random_state=200)
clf.fit(X_train,Y_train)


MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(10, 5), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=200,
       shuffle=True, solver='lbfgs', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [25]:
y_pred=clf.predict(X_test)
accuracy=accuracy_score(Y_test,y_pred)*100
print("Execution time: ",time.time()-start_time)
print("Test Accuracy: ",round(accuracy,1),"%")

Execution time:  0.8626599311828613
Test Accuracy:  48.5 %
